# Site settings
title: AlaaMutasim
url: "http://AlaaMutasim.github.io/"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
 This blog is about using Python for Statistics.

# Your information
email: alaamutasim176@gmail.com
author: Alaa Mutasim
avatar: "https://github.com/AlaaMutasim/AlaaMutasim.github.io/blob/gh-pages/abdulaziz-mohammed-530xuFR5YRU-unsplash.jpg?raw=true"
profile:  My name is Alaa Mutasim, you can call me Alaa. I did Statistics and Computation in B.Sc. degree. I am Python programmer.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:alaamutasim176@gmail.com"
  GitHub: "https://github.com/AlaaMutasim"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
